export type TFirmRu = {
    id: number,
    full_name?: string,
    short_name?: string,
    legal_form?: string,
    inn?: string,
    kpp?: string,
    ogrn?: string,
    legal_address?: string,
    actual_address?: string,
    phone?: string,
    email?: string,
    bank_account?: string,
    bank_bik?: string,
    bank_name?: string,
    correspondent_account?: string,
    okpo?: string,
    okved?: string,
    oktmo?: string,
    okfs?: string,
    okopf?: string,
    registration_date?: string,
    ceo_name?: string,
    capital?: number
}

export function NoteRu(): string {
    return [
        `full_name: string - Official name of the company - example - Общество с ограниченной ответственностью "Пример"`,
        `short_name: string - Short name of the company - example - ООО "Пример"`,
        `legal_form: string - Organization type - example - ООО`,
        `inn: string - Taxpayer identification number - example - 7701234567`,
        `kpp: string - Reason code for registration - example - 770101001`,
        `ogrn: string - Primary state registration number - example - 1157746444444`,
        `legal_address: string - Company registration address - example - г. Москва, ул. Ленина, д. 10`,
        `actual_address: string - Place of business - example - г. Москва, ул. Ленина, д. 12`,
        `phone: string - Contact phone number - example - +7 (495) 123-45-67`,
        `email: string - Company email - example - info@example.com`,
        `bank_account: string - Current account number - example - 40702810999999999999`,
        `bank_bik: string - Bank identification code - example - 044525225`,
        `bank_name: string - Name of servicing bank - example - ПАО "Сбербанк"`,
        `correspondent_account: string - Correspondent bank account - example - 30101810200000000225`,
        `okpo: string - Company code in the okpo - example - 12345678`,
        `okved: string - Main type of economic activity - example - 62.01`,
        `oktmo: string - Code of municipal territories - example - 45348000`,
        `okfs: string - Code of form of ownership - example - 16`,
        `okopf: string - Code of organizational and legal form - example - 12300`,
        `registration_date: Date - Date of company registration - example - 2020-03-15`,
        `ceo_name: string - General director - example - Иванов Иван Иванович`,
        `capital: number - Amount of authorized capital - example - 100000`,
    ].join('\n')
}